on:
  workflow_dispatch:
  #schedule:
  #- cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install R packages
        run: R -e 'source("install.R")' 
# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        run: /usr/local/bin/r forecast_model.R || true
